### ISSUE TITLE
Loading paths pointing to local paths on `hopper`

### ISSUE THREAD

**Issue by Hugemiler** [Klepac-Ceraj-Lab/MicrobiomeAgeModel2024#9]
For the beta release, we must substitute the loading procedure for something:
1. machine-agnostic
2. preferably, that can consume the Data Dryad via API or `curl` when setting up the environment 
3. that can potentially work automatically on installation? @kescobo

**Comment by kescobo** [comment]
Yes - once the data is on dryad, you should use DataDeps.jl or DataToolkit.jl to get the data and manage paths

**Comment by Hugemiler** [comment]
Closed by #12
